services:
  db:
    image: mysql:8.0
    container_name: kiefersink-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kiefersink_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - kiefersinknetwork

  backend:
    build: .
      # context: ./kiefersink-backend/sbkieferms
      # dockerfile: Dockerfile
    image: kiefersink-backend
    container_name: kiefersink-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kiefersink_db
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - FILE_UPLOAD_DIR=/app/uploads
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      # - ./kiefersink-backend/sbkieferms/uploads:/app/uploads
    networks:
      - kiefersinknetwork

volumes:
  db_data:

networks:
  kiefersinknetwork:
    external: true
